### ISSUE TITLE
git revision policy

### ISSUE THREAD

**Issue by squaremo** [squaremo/image-reflector-controller#15]
So far there's a semver policy for selecting images, which selects the highest version within a given range.

Another variety of policy that we use everywhere in the Weave Cloud dev environment is "run the most recently built image", which is calculated by looking at the build timestamp. This is easily tripped up, though, in a few ways:

 - sometimes an image build will result in an image that already exists (e.g., if you revert a code change), which will have the old timestamp
 - getting the build timestamp relies on interpreting fields and labels in the image metadata -- there's no single timestamp field.

What's _actually_ required is _the image built from the most recent commit_ (.. on a particular branch). The git revision policy would calculate that by looking at the git repository itself, to determine which among the available images should be selected.

```yaml
kind: ImagePolicy
spec:
  imageRepository:
    name: flux-image
  policy:
    gitRevision:
      gitRepositoryRef:
        name: flux-repo
      branch: main
```
